# Prints a confirmation whenever a player is given a loadout
verbose: true
# Prints debug messages
debug: false
# Adds a ms delay if needed for plugin compatibility
delay: 0

# Filters are processed in the order they are written except anything marked as "all" is always processed before all other entries
items:
    # SteamID
    all:
        # Rank, the name of the server rank defined in config_remoteadmin.txt. Set to none for only players without a rank.
        donator:
            # Class, check #resources in the SMOD discord server for class names
            all:
                # Percentage chance for item group to spawn
                - 50:
                    # Items to spawn, must be all caps, check #resources in the SMOD discord server for item names. You can start with REMOVEITEMS and REMOVEAMMO to delete the existing items/ammo.
                    # All weapons spawn with one mag/clip loaded which cannot be removed, giving ammo adds the ammo directly to the player instead of spawning it as an item in their inventory.
                    # This example has a 50% chance to spawn a coin to all players with the rank donator
                    - COIN
                - 10:
                    - MEDKIT
            SCIENTIST:
                - 10:
                    - REMOVEITEMS
                    - MAJOR_SCIENTIST_KEYCARD
                    - MEDKIT
                - 5:
                    - REMOVEITEMS
                    - REMOVEAMMO
                    - USP
                    - DROPPED_9
                    - DROPPED_9
                    - MAJOR_SCIENTIST_KEYCARD
                    - MEDKIT
        moderator:
            all:
                - 30:
                    - FLASHLIGHT
    # Quotes are important on SteamIDs
    "76561198022373616":
        all:
            all:
                - 100:
                    - MICROHID
                    - MICROHID
                    - MICROHID
                    - MICROHID
                    - MICROHID
                    - MICROHID
                    - MICROHID
                    - MICROHID