debug: false
verbose: true

# Filters are processed in the order they are written except anything marked as "all" is always processed before all other entries
items:
    # SteamID
    all:
        # Rank, the name of the server rank defined in config_remoteadmin.txt. NOT THE BADGE, THE VARIABLE NAME
        donator:
            # Class, check #resources in the SMOD discord server for class names
            all:
                # Percentage chance for item group to spawn
                - 50:
                    # Items to spawn, must be all caps, check #resources in the SMOD discord server for item names. Start with REMOVEALL to delete the default items/previously added bundles.
                    - COIN
                - 10:
                    - MEDKIT
            SCIENTIST:
                - 10:
                    - REMOVEALL
                    - MAJOR_SCIENTIST_KEYCARD
                    - MEDKIT
                - 5:
                    - REMOVEALL
                    - USP
                    - MAJOR_SCIENTIST_KEYCARD
                    - MEDKIT
        moderator:
            all:
                - 30:
                    - FLASHLIGHT
    "76561198022373616":
        all:
            all:
                - 100:
                    - MICROHID
                    - MICROHID
                    - MICROHID
                    - MICROHID
                    - MICROHID
                    - MICROHID
                    - MICROHID
                    - MICROHID